var x = null;
var y = undefined;
var isXMore = x <= y;
var isXMore = x == y;
var isXMore = x === y;
var isXMore = x !== y;
var isXMore = x == y;
console.log(false == 0);
console.log(true == 1);
console.log(null == undefined);
console.log(NaN == NaN);